### ISSUE TITLE
Incompatibility with Foundation 5 Tabs?

### ISSUE THREAD

**Issue by 1903Daniel** [liabru/jquery-match-height#124]
Please find my codepen here -> http://codepen.io/wutz/pen/KrYaxJ

For the divs wrapped in the section on the top (class testDiv), it works like a charm.
For foundation 5 tabs (class testTab), it does not.

**Comment by DavidBruchmann** [comment]
I don't see the problem.
If you never want the text below the tab-content being adjusted in the height, then just assign a height to the class tabs-content, perhaps even dynamically by JS. Default behavior is that the height of the current tab determines the height of the following content - but it can be reasonable to avoid jumping of the following content, then just assign a static height to the tab-container.
I don't see that match-height is faulting here because it's always only one sub-container visible and match-height is not considering invisible parts.

**Comment by liabru** [comment]
Actually @DavidBruchmann matchHeight supports invisible content :)

@1903Daniel the reason is that the default is to match by row. Since your tabs are only one element per row, then nothing happens. Try disabling `byRow`:

    $('.testTab').matchHeight({ byRow: false });

**Comment by 1903Daniel** [comment]
@liabru :+1:  works like a charm, thank you very much :-)

**Comment by DavidBruchmann** [comment]
@liabru thanks for the info, good to know!
