### ISSUE TITLE
Not working with Bootstrap tabs / Jquery Edge?

### ISSUE THREAD

**Issue by denkmalimmo** [liabru/jquery-match-height#70]
I've seen this has been an issue before and should be solved, but unfortunately I can't get it to work with bootstrap tabs.

JSFiddle:
https://jsfiddle.net/a7h2fsbt/2/

Your own Fiddle on this topic seems also to have stopped working with Jquery-Edge:
http://jsfiddle.net/liabru/ZAym4/

Maybe you could have a look at it.

**Comment by liabru** [comment]
Looks like there's been a regression. I tested with 0.6.0 and it seems to work:
https://github.com/liabru/jquery-match-height/releases/tag/0.6.0

Can you confirm?

**Comment by denkmalimmo** [comment]
Thanks for your fast reply!
Indeed my JSFiddle is working as expected with version 0.6.0 and jQuery 1.11.0.

https://jsfiddle.net/a7h2fsbt/3/

0.6.0 + jQuery 1.11.0    -> working
0.6.0 + jQuery edge      -> broken
master + jQuery 1.11.0 -> broken
master +  jQuery edge  -> broken

Anyway, I'm going to use 0.6.0  + jQuery 1.11.0, so I'm fine so far. Thanks for your help!

**Comment by liabru** [comment]
I looked at this again and it appears the reason the fiddle didn't appear to work for me was actually because the resource link was erroring (refused MIME type ('text/plain') is not executable, and strict MIME type checking is enabled).

I switched to using via rawgit instead i.e.
https://rawgit.com/liabru/jquery-match-height/master/jquery.matchHeight-min.js

And I can no longer see a problem, can you confirm?

**Comment by denkmalimmo** [comment]
Indeed, working for me now:

http://jsfiddle.net/liabru/ZAym4/

Thank you for your efforts.
